import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './styles/globals.css'
import { SimpleHeader } from '@/components/SimpleHeader'

const geistSans = localFont({
	src: './styles/fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900'
})
const geistMono = localFont({
	src: './styles/fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900'
})

export const metadata: Metadata = {
	title: 'Pages',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<link
				rel='icon'
				type='image/svg+xml'
				href='https://qualitaet-ist-mehrwert.de/wp-content/uploads/microsoft-to-do-365-logo.png'
			/>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<SimpleHeader />
				{children}
			</body>
		</html>
	)
}
